# Generated by Django 2.2 on 2019-04-15 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 15, 18, 35, 52, 89921, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
